apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccommander
  labels:
    app: ccommander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccommander
  template:
    metadata:
      labels:
        app: ccommander
    spec:
      containers:
        - name: ccommander
          image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis_image.repository}}:{{ .Values.redis_image.tag }}
          ports:
            - containerPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccollector
  labels:
    app: ccollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccollector
  template:
    metadata:
      labels:
        app: ccollector
    spec:
      containers:
        - name: ccollector
          image: {{ .Values.collector_image.repository}}:{{ .Values.collector_image.tag }}
          ports:
            - ccollector: 8001