apiVersion: v1
kind: Service
metadata:
  name: ccommander-nip
  labels:
    app: ccommander
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8000
      nodePort: 31081
      name: http
  selector:
    app: ccommander

---
apiVersion: v1
kind: Service
metadata:
  name: redis-nip
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 31082
      name: tcp
  selector:
    app: redis