name: Python CI Steps Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        sudo make test
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build
      run: |
        sudo docker build ./docker -t tgionfriddo/config_commander:1.2
    - name: docker push
      run: |
        sudo docker push tgionfriddo/config_commander:1.2

